services:
  banking-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: banking-service:latest
    container_name: banking-service-container
    environment:
      - QUARKUS_DATASOURCE_USERNAME=eduardo
      - QUARKUS_DATASOURCE_PASSWORD=eduardo
      - QUARKUS_DATASOURCE_HOST=postgres-db-alura
      - QUARKUS_DATASOURCE_PORT=5432
    ports:
      - 8181:8181
    depends_on:
      - postgres-db-alura

  postgres-db-alura:
    image: postgres:14
    container_name: postgres-db-alura-container
    environment:
      - POSTGRES_USER=eduardo
      - POSTGRES_PASSWORD=eduardo
      - POSTGRES_DB=agencia
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
