create table if not exists endereco(
    id integer generated by default as identity primary key,
    rua varchar(100) not null,
    logradouro varchar(100) not null,
    complemento varchar(100) not null,
    numero int not null
);

create table if not exists agencia(
    id integer generated by default as identity primary key,
    nome varchar(100) not null,
    razao_social varchar(100) not null,
    cnpj varchar(18) not null,
    endereco_id integer not null unique references endereco(id)
);
