quarkus.http.port=8181

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:eduardo}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:eduardo}
quarkus.datasource.jdbc.url=jdbc:postgresql://${QUARKUS_DATASOURCE_HOST:localhost}:${QUARKUS_DATASOURCE_PORT:5432}/agencia

quarkus.rest-client.situacao-cadastral-api.url=http://localhost:8181
